Repository puppetlabs/cisco_ios, pull requests merged in 2018-07, with the labels that each got.

#225 (maint) add tags to metadata
  metadata.json
Labels: maintenance

#212 (FM-7067) Send a newline on Config T mode to clear prompt
  lib/puppet/util/network_device/cisco_ios/device.rb
Labels: bugfix

#232 (FM-6952) Add types and providers for configuring AAA
  README.md
  examples/ios_aaa_accounting.pp
  examples/ios_aaa_authentication.pp
  examples/ios_aaa_authorization.pp
  examples/ios_aaa_new_model.pp
  examples/ios_aaa_session_id.pp
  lib/puppet/provider/ios_aaa_accounting/command.yaml
  lib/puppet/provider/ios_aaa_accounting/ios.rb
  lib/puppet/provider/ios_aaa_authentication/command.yaml
  lib/puppet/provider/ios_aaa_authentication/ios.rb
  lib/puppet/provider/ios_aaa_authorization/command.yaml
  lib/puppet/provider/ios_aaa_authorization/ios.rb
  lib/puppet/provider/ios_aaa_new_model/command.yaml
  lib/puppet/provider/ios_aaa_new_model/ios.rb
  lib/puppet/provider/ios_aaa_session_id/command.yaml
  lib/puppet/provider/ios_aaa_session_id/ios.rb
  lib/puppet/type/ios_aaa_accounting.rb
  lib/puppet/type/ios_aaa_authentication.rb
  lib/puppet/type/ios_aaa_authorization.rb
  lib/puppet/type/ios_aaa_new_model.rb
  lib/puppet/type/ios_aaa_session_id.rb
  lib/puppet/util/network_device/cisco_ios/command.yaml
  lib/puppet/util/network_device/cisco_ios/device.rb
  lib/puppet_x/puppetlabs/cisco_ios/utility.rb
  spec/acceptance/ios_aaa_accounting_spec.rb
  spec/acceptance/ios_aaa_authentication_spec.rb
  spec/acceptance/ios_aaa_authorization_spec.rb
  spec/acceptance/ios_aaa_new_model_spec.rb
  spec/acceptance/ios_aaa_session_id_spec.rb
  spec/unit/puppet/provider/ios_aaa_accounting/ios_aaa_accounting_spec.rb
  spec/unit/puppet/provider/ios_aaa_accounting/test_data.yaml
  spec/unit/puppet/provider/ios_aaa_authentication/ios_aaa_authentication_spec.rb
  spec/unit/puppet/provider/ios_aaa_authentication/test_data.yaml
  spec/unit/puppet/provider/ios_aaa_authorization/ios_aaa_authorization_spec.rb
  spec/unit/puppet/provider/ios_aaa_authorization/test_data.yaml
  spec/unit/puppet/provider/ios_aaa_new_model/ios_aaa_new_model_spec.rb
  spec/unit/puppet/provider/ios_aaa_new_model/test_data.yaml
  spec/unit/puppet/provider/ios_aaa_session_id/ios_aaa_session_id_spec.rb
  spec/unit/puppet/provider/ios_aaa_session_id/test_data.yaml
  spec/unit/puppet/type/ios_aaa_accounting_spec.rb
  spec/unit/puppet/type/ios_aaa_authentication_spec.rb
  spec/unit/puppet/type/ios_aaa_authorization_spec.rb
  spec/unit/puppet/type/ios_aaa_new_model_spec.rb
  spec/unit/puppet/type/ios_aaa_session_id_spec.rb
Labels: feature
