Repository puppetlabs/cisco_ios, pull requests merged in 2019-09, with the labels that each got.

#379 (maint) - VRF Fix
  lib/puppet/provider/ntp_server/command.yaml
  spec/acceptance/ntp_server_spec.rb
  spec/spec_helper_acceptance.rb
Labels: bugfix

#381 (FM-7815) ios_access_list and ios_acl_entry deprecation changes
  lib/puppet/provider/ios_access_list/cisco_ios.rb
  lib/puppet/provider/ios_acl_entry/cisco_ios.rb
  lib/puppet/transport/cisco_ios.rb
  spec/acceptance/ios_access_list_spec.rb
  spec/acceptance/ios_acl_entry_spec.rb
Labels: maintenance

#352 (FM-7741) add XE support in ios_aaa_authentication
  README.md
  TestMatrix.md
  lib/puppet/provider/ios_aaa_authentication/cisco_ios.rb
  lib/puppet/provider/ios_aaa_authentication/command.yaml
  lib/puppet/type/ios_aaa_authentication.rb
  spec/acceptance/ios_aaa_accounting_spec.rb
  spec/acceptance/ios_aaa_authentication_spec.rb
  spec/unit/puppet/provider/ios_aaa_accounting/test_data.yaml
  spec/unit/puppet/provider/ios_aaa_authentication/cisco_ios_spec.rb
  spec/unit/puppet/provider/ios_aaa_authentication/test_data.yaml
Labels: feature

#378 (FM-8438) - Fix to make the attributes of syslog_settings `console` and `monitor` idempotent
  lib/puppet/provider/syslog_settings/cisco_ios.rb
  spec/unit/puppet/provider/syslog_settings/cisco_ios_spec.rb
Labels: bugfix

#382 (FM-8498) Fixes for acceptance test failures
  lib/puppet/provider/ios_acl/cisco_ios.rb
  lib/puppet/provider/ios_acl/command.yaml
  spec/acceptance/ios_ntp_access_group_spec.rb
Labels: maintenance

#380 (FM-8485) - Addition of CODEOWNERS file
  CODEOWNERS
Labels: maintenance

#386 (FM-8509) - 1.1.0 Merge Back
  CHANGELOG.md
  metadata.json
Labels: maintenance

#384 (FM-8437) - tacacs idempotency fixes
  lib/puppet/provider/tacacs_global/cisco_ios.rb
  lib/puppet/provider/tacacs_server_group/cisco_ios.rb
  spec/unit/puppet/provider/tacacs_global/cisco_ios_spec.rb
  spec/unit/puppet/provider/tacacs_server_group/cisco_ios_spec.rb
Labels: bugfix

#389 (maint) - Fix for syslog_Server
  lib/puppet/provider/syslog_server/cisco_ios.rb
  lib/puppet/provider/syslog_server/command.yaml
  spec/unit/puppet/provider/syslog_server/cisco_ios_spec.rb
  spec/unit/puppet/provider/syslog_server/test_data.yaml
Labels: bugfix

#392 pdksync - (maint) update pdk-templates
  Rakefile
  metadata.json
  spec/default_facts.yml
Labels: maintenance

#390 (maint) Improve wording for known_hosts_file
  lib/puppet/transport/schema/cisco_ios.rb
Labels: bugfix

#394 (maint) - Fix for vrf type
  lib/puppet/provider/vrf/command.yaml
  spec/acceptance/vrf_spec.rb
  spec/spec_helper_acceptance.rb
Labels: bugfix
