Repository puppetlabs/cisco_ios, pull requests merged in 2019-06, with the labels that each got.

#317 (FM-7755) - Port Channel update to account for XE
  README.md
  lib/puppet/provider/port_channel/command.yaml
  spec/acceptance/port_channel_spec.rb
Labels: maintenance

#325 (maint) Fix for Tacas Global Test
  spec/acceptance/tacacs_global_spec.rb
Labels: maintenance

#326 (maint) - Network Interface Test Fix
  spec/acceptance/network_interface_spec.rb
Labels: maintenance

#328 (maint) - Tacacs Server Tests Fix
  spec/acceptance/tacacs_server_spec.rb
Labels: maintenance

#329 (maint) - Fix tests of Cisco 4507r
  README.md
  lib/puppet/provider/radius_server/command.yaml
  spec/acceptance/radius_server_spec.rb
  spec/acceptance/tacacs_server_spec.rb
Labels: maintenance

#331 pdksync - Update to current PDK templates and cleanups
  .fixtures.yml
  .sync.yml
  Gemfile
  metadata.json
  spec/spec_helper.rb
Labels: maintenance

#333 (MODULES-9268) - v1.0.0 Merge Back
  CHANGELOG.md
  metadata.json
Labels: maintenance

#336 (maint) Update the connection prompt to match on confirmation prompts
  lib/puppet/transport/command.yaml
Labels: bugfix

#334 (FM-7757) Add IOS_radius_global type and provider
  README.md
  lib/puppet/provider/ios_radius_global/cisco_ios.rb
  lib/puppet/provider/ios_radius_global/command.yaml
  lib/puppet/type/ios_radius_global.rb
  lib/puppet_x/puppetlabs/cisco_ios/utility.rb
  spec/acceptance/ios_radius_global_spec.rb
  spec/unit/puppet/provider/ios_radius_global/cisco_ios_spec.rb
  spec/unit/puppet/provider/ios_radius_global/test_data.yaml
Labels: enhancement

#339 (maint) Reduce debug noise from send_command
  lib/puppet/transport/cisco_ios.rb
Labels: maintenance

#340 (maint) Improve readability of error messages returned from the device
  lib/puppet/transport/cisco_ios.rb
Labels: maintenance
