Repository puppetlabs/cisco_ios, pull requests merged in 2019-10, with the labels that each got.

#395 (maint) - Additional Fix for vrf type
  spec/acceptance/vrf_spec.rb
Labels: bugfix

#396 (FM-8435) - Exclude a VRF from being set in tacacs_global
  TestMatrix.md
  lib/puppet/provider/tacacs_global/cisco_ios.rb
  spec/acceptance/tacacs_global_spec.rb
  spec/unit/puppet/provider/tacacs_global/cisco_ios_spec.rb
  spec/unit/puppet/provider/tacacs_global/test_data.yaml
Labels: bugfix

#397 (FM-8501) Add vrf support to ios_interface
  REFERENCE.md
  lib/puppet/provider/ios_interface/cisco_ios.rb
  lib/puppet/provider/ios_interface/command.yaml
  lib/puppet/type/ios_interface.rb
  spec/acceptance/ios_interface_spec.rb
  spec/spec_helper_acceptance.rb
  spec/unit/puppet/provider/ios_interface/test_data.yaml
Labels: enhancement

#398 (maint) Remove Mgm-vrf and add VRF ModeState
  lib/puppet/transport/cisco_ios.rb
  spec/acceptance/ntp_server_spec.rb
  spec/acceptance/snmp_notification_receiver_spec.rb
  spec/acceptance/syslog_server_spec.rb
  spec/spec_helper_acceptance.rb
  spec/unit/puppet/provider/ntp_server/test_data.yaml
  spec/unit/puppet/provider/syslog_server/test_data.yaml
Labels: bugfix

#403 (FM-8608) - Addition of attribute `directed_request` to `tacacs_global`
  lib/puppet/provider/tacacs_global/cisco_ios.rb
  lib/puppet/provider/tacacs_global/command.yaml
  spec/acceptance/tacacs_global_spec.rb
  spec/unit/puppet/provider/tacacs_global/test_data.yaml
Labels: enhancement

#405 (maint) clean up acceptance setup to work with new pipelines
  spec/spec_helper_acceptance.rb
Labels: maintenance
