Repository puppetlabs/cisco_ios, pull requests merged in 2019-07, with the labels that each got.

#347 (FM-7740) Add XE support for ios_aaa_accounting
  .gitignore
  .pdkignore
  .sync.yml
  README.md
  lib/puppet/provider/ios_aaa_accounting/cisco_ios.rb
  lib/puppet/provider/ios_aaa_accounting/command.yaml
  lib/puppet/provider/network_interface/cisco_ios.rb
  lib/puppet/transport/cisco_ios.rb
  lib/puppet/transport/command.yaml
  lib/puppet/type/ios_aaa_accounting.rb
  spec/acceptance/ios_aaa_accounting_spec.rb
  spec/acceptance/radius_server_spec.rb
  spec/fixtures/inventory.example.yml
  spec/spec_helper_acceptance.rb
  spec/unit/puppet/provider/ios_aaa_accounting/test_data.yaml
  spec/unit/puppet/provider/network_interface/cisco_ios_spec.rb
  spec/unit/puppet/provider/network_interface/test_data.yaml
Labels: enhancement

#341 (FM-7747) IOS Network DNS Created
  README.md
  lib/puppet/provider/ios_network_dns/cisco_ios.rb
  lib/puppet/provider/ios_network_dns/command.yaml
  lib/puppet/type/ios_network_dns.rb
  spec/acceptance/ios_network_dns_spec.rb
  spec/unit/puppet/provider/ios_network_dns/cisco_ios_spec.rb
  spec/unit/puppet/provider/ios_network_dns/test_data.yaml
  spec/unit/puppet/type/ios_network_dns_spec.rb
Labels: feature

#343 (FM-7764) - Functionality added to Syslog Settings
  README.md
  lib/puppet/provider/syslog_settings/cisco_ios.rb
  lib/puppet/provider/syslog_settings/command.yaml
  spec/acceptance/syslog_settings_spec.rb
  spec/unit/puppet/provider/syslog_settings/cisco_ios_spec.rb
  spec/unit/puppet/provider/syslog_settings/test_data.yaml
Labels: enhancement

#344 (FM-7764) - IOS Additional Syslog Settings created
  README.md
  lib/puppet/provider/ios_additional_syslog_settings/cisco_ios.rb
  lib/puppet/provider/ios_additional_syslog_settings/command.yaml
  lib/puppet/type/ios_additional_syslog_settings.rb
  spec/acceptance/ios_additional_syslog_settings_spec.rb
  spec/unit/puppet/provider/ios_additional_syslog_settings/cisco_ios_spec.rb
  spec/unit/puppet/provider/ios_additional_syslog_settings/test_data.yaml
  spec/unit/puppet/type/ios_additional_syslog_settings.rb
Labels: feature

#351 (FM-7764) Exclusion added for ios_additional_syslog_settings tests
  README.md
  lib/puppet/provider/ios_additional_syslog_settings/command.yaml
  lib/puppet/provider/syslog_settings/cisco_ios.rb
  spec/acceptance/ios_additional_syslog_settings_spec.rb
Labels: bugfix

#354 Fix docs URL for forge publishing
  README.md
Labels: maintenance

#346 (FM-7760) Add ios_snmp_global type and provider
  README.md
  lib/puppet/provider/ios_snmp_global/cisco_ios.rb
  lib/puppet/provider/ios_snmp_global/command.yaml
  lib/puppet/type/ios_snmp_global.rb
  spec/acceptance/ios_snmp_global_spec.rb
  spec/unit/puppet/provider/ios_snmp_global/cisco_ios_spec.rb
  spec/unit/puppet/provider/ios_snmp_global/test_data.yaml
  spec/unit/puppet/type/ios_snmp_global_spec.rb
Labels: feature
