Repository puppetlabs/cisco_ios, pull requests merged in 2019-11, with the labels that each got.

#406 (FM-8705) - Exclusions added for Cisco-3560
  TestMatrix.md
  lib/puppet/provider/ios_ntp_config/command.yaml
  lib/puppet/provider/network_interface/command.yaml
  lib/puppet/provider/ntp_server/command.yaml
  lib/puppet/provider/radius_server/command.yaml
  spec/acceptance/ios_interface_spec.rb
  spec/acceptance/ios_ntp_config_spec.rb
  spec/acceptance/network_interface_spec.rb
  spec/acceptance/ntp_server_spec.rb
  spec/acceptance/radius_server_spec.rb
  spec/acceptance/snmp_notification_receiver_spec.rb
  spec/acceptance/syslog_server_spec.rb
  spec/acceptance/tacacs_server_group_spec.rb
  spec/acceptance/tacacs_server_spec.rb
  spec/acceptance/vrf_spec.rb
  spec/spec_helper_acceptance.rb
Labels: bugfix

#407 (MODULES-10058) - ntp-server fix
  lib/puppet/provider/ntp_server/command.yaml
  spec/acceptance/ntp_server_spec.rb
Labels: bugfix

#404 (FM-8572) - Addition of type ios_ip
  REFERENCE.md
  TestMatrix.md
  lib/puppet/provider/ios_ip/cisco_ios.rb
  lib/puppet/provider/ios_ip/command.yaml
  lib/puppet/type/ios_ip.rb
  spec/acceptance/ios_ip_spec.rb
  spec/unit/puppet/provider/ios_ip/cisco_ios_spec.rb
  spec/unit/puppet/provider/ios_ip/test_data.yaml
  spec/unit/puppet/type/ios_ip_spec.rb
Labels: enhancement

#408 (FM-8572) - Addition of type ios_cef
  REFERENCE.md
  TestMatrix.md
  lib/puppet/provider/ios_cef/cisco_ios.rb
  lib/puppet/provider/ios_cef/command.yaml
  lib/puppet/provider/ios_ntp_access_group/cisco_ios.rb
  lib/puppet/type/ios_cef.rb
  spec/acceptance/ios_cef_spec.rb
  spec/unit/puppet/provider/ios_cef/cisco_ios_spec.rb
  spec/unit/puppet/provider/ios_cef/test_data.yaml
  spec/unit/puppet/type/ios_cef_spec.rb
Labels: feature

#409 (FM-8572) - Addition of `route_cache_cef` to `ios_interface`
  REFERENCE.md
  TestMatrix.md
  lib/puppet/provider/ios_interface/cisco_ios.rb
  lib/puppet/provider/ios_interface/command.yaml
  lib/puppet/type/ios_interface.rb
  spec/acceptance/ios_interface_spec.rb
  spec/unit/puppet/provider/ios_interface/test_data.yaml
Labels: feature

#410 (FM-8745) - v1.2.0 Release Prep
  CHANGELOG.md
  metadata.json
Labels: maintenance

#411 (maint) - v1.2.0 Release Mergeback
  CHANGELOG.md
  metadata.json
Labels: maintenance

#412 pdksync - (maint) enable simplecove and minor cleanups
  .gitlab-ci.yml
  .sync.yml
  .travis.yml
  spec/spec_helper.rb
Labels: maintenance

#413 (MODULES-10120) enable simplecov; update to PDK 1.14.1; minor cleanups
  .rubocop.yml
  .sync.yml
  appveyor.yml
  metadata.json
Labels: maintenance
