Repository puppetlabs/cisco_ios, pull requests merged in 2019-08, with the labels that each got.

#245 (FM-7222) Error out instead of attemping to delete default Cisco VLANs
  lib/puppet/provider/network_vlan/cisco_ios.rb
  lib/puppet/provider/network_vlan/command.yaml
  lib/puppet/transport/cisco_ios.rb
  lib/puppet/transport/command.yaml
  spec/acceptance/network_vlan_spec.rb
  spec/unit/puppet/provider/network_vlan/cisco_ios_spec.rb
  spec/unit/puppet/provider/network_vlan/test_data.yaml
Labels: bugfix

#359 (maint) Update PDK templates and fix code coverage
  .rubocop.yml
  .travis.yml
  .vscode/extensions.json
  Gemfile
  Rakefile
  appveyor.yml
  lib/puppet/provider/banner/cisco_ios.rb
  lib/puppet/provider/ios_additional_syslog_settings/cisco_ios.rb
  lib/puppet/provider/ios_snmp_global/cisco_ios.rb
  lib/puppet/provider/network_dns/cisco_ios.rb
  lib/puppet/provider/network_interface/cisco_ios.rb
  lib/puppet/provider/network_snmp/cisco_ios.rb
  lib/puppet/provider/network_trunk/cisco_ios.rb
  lib/puppet/provider/network_vlan/cisco_ios.rb
  lib/puppet/provider/ntp_auth_key/cisco_ios.rb
  lib/puppet/provider/ntp_config/cisco_ios.rb
  lib/puppet/provider/ntp_server/cisco_ios.rb
  lib/puppet/provider/port_channel/cisco_ios.rb
  lib/puppet/provider/radius_global/cisco_ios.rb
  lib/puppet/provider/radius_server/cisco_ios.rb
  lib/puppet/provider/radius_server_group/cisco_ios.rb
  lib/puppet/provider/snmp_community/cisco_ios.rb
  lib/puppet/provider/snmp_notification/cisco_ios.rb
  lib/puppet/provider/snmp_notification_receiver/cisco_ios.rb
  lib/puppet/provider/snmp_user/cisco_ios.rb
  lib/puppet/provider/syslog_server/cisco_ios.rb
  lib/puppet/provider/syslog_settings/cisco_ios.rb
  lib/puppet/provider/tacacs_global/cisco_ios.rb
  lib/puppet/provider/tacacs_server/cisco_ios.rb
  lib/puppet/provider/tacacs_server_group/cisco_ios.rb
  metadata.json
  spec/spec_helper.rb
  spec/spec_helper_local.rb
  spec/unit/puppet/provider/ios_network_trunk/cisco_ios_spec.rb
  spec/unit/puppet/provider/ios_radius_global/cisco_ios_spec.rb
Labels: maintenance

#349 (FM-8310) idempotency fixes for the silent failures on jenkins
  README.md
  TestMatrix.md
  lib/puppet/provider/ios_aaa_accounting/command.yaml
  lib/puppet/provider/ios_network_dns/cisco_ios.rb
  lib/puppet/provider/ios_network_trunk/cisco_ios.rb
  lib/puppet/provider/ios_radius_global/cisco_ios.rb
  lib/puppet/provider/network_dns/cisco_ios.rb
  lib/puppet/provider/ntp_config/cisco_ios.rb
  lib/puppet/provider/snmp_notification/cisco_ios.rb
  lib/puppet/provider/tacacs_global/command.yaml
  lib/puppet/provider/tacacs_server/cisco_ios.rb
  lib/puppet/type/ios_aaa_accounting.rb
  spec/acceptance/ios_network_trunk_spec.rb
  spec/acceptance/ios_radius_global_spec.rb
  spec/acceptance/network_interface_spec.rb
  spec/acceptance/network_trunk_spec.rb
  spec/acceptance/ntp_auth_key_spec.rb
  spec/acceptance/ntp_config_spec.rb
  spec/acceptance/ntp_server_spec.rb
  spec/acceptance/port_channel_spec.rb
  spec/acceptance/radius_global_spec.rb
  spec/acceptance/radius_server_spec.rb
  spec/acceptance/snmp_notification_spec.rb
  spec/acceptance/snmp_user_spec.rb
  spec/acceptance/tacacs_global_spec.rb
  spec/acceptance/tacacs_server_spec.rb
  spec/spec_helper_acceptance.rb
  spec/unit/puppet/provider/ios_aaa_accounting/test_data.yaml
  spec/unit/puppet/provider/ios_network_dns/cisco_ios_spec.rb
  spec/unit/puppet/provider/ios_network_dns/test_data.yaml
  spec/unit/puppet/provider/ios_network_trunk/cisco_ios_spec.rb
  spec/unit/puppet/provider/ios_radius_global/cisco_ios_spec.rb
  spec/unit/puppet/provider/network_dns/cisco_ios_spec.rb
  spec/unit/puppet/provider/network_dns/test_data.yaml
  spec/unit/puppet/provider/ntp_config/cisco_ios_spec.rb
  spec/unit/puppet/provider/ntp_config/test_data.yaml
  spec/unit/puppet/provider/tacacs_server/cisco_ios_spec.rb
  spec/unit/puppet/provider/tacacs_server/test_data.yaml
Labels: maintenance

#361 (maint) environmental acceptance test fixes
  .sync.yml
  Gemfile
  lib/puppet/provider/ios_network_trunk/cisco_ios.rb
  lib/puppet/provider/ios_radius_global/cisco_ios.rb
  spec/unit/puppet/provider/ios_network_trunk/cisco_ios_spec.rb
  spec/unit/puppet/provider/ios_radius_global/cisco_ios_spec.rb
Labels: maintenance

#366 (FM-7774) Updated README and metadata to include XE support
  README.md
  TestMatrix.md
  metadata.json
Labels: maintenance

#365 (MODULES-9465) ios_radius_global: fix spurious whitespace in attributes returned from device
  lib/puppet/provider/ios_radius_global/command.yaml
Labels: bugfix

#368 (FM-7818) - Addition of attributes to banner type
  lib/puppet/provider/banner/cisco_ios.rb
  lib/puppet/provider/banner/command.yaml
  spec/acceptance/banner_spec.rb
  spec/unit/puppet/provider/banner/test_data.yaml
Labels: enhancement

#348 (FM-7760) add ios_interface
  README.md
  TestMatrix.md
  lib/puppet/provider/ios_interface/cisco_ios.rb
  lib/puppet/provider/ios_interface/command.yaml
  lib/puppet/provider/ios_network_dns/cisco_ios.rb
  lib/puppet/type/ios_interface.rb
  spec/acceptance/ios_interface_spec.rb
  spec/unit/puppet/provider/ios_interface/cisco_ios_spec.rb
  spec/unit/puppet/provider/ios_interface/test_data.yaml
  spec/unit/puppet/type/ios_interface.rb
Labels: feature

#360 (FM-7758) Add type ios_radius_server_group
  README.md
  lib/puppet/provider/ios_radius_server_group/cisco_ios.rb
  lib/puppet/provider/ios_radius_server_group/command.yaml
  lib/puppet/type/ios_radius_server_group.rb
  spec/acceptance/ios_radius_server_group_spec.rb
  spec/unit/puppet/provider/ios_radius_server_group/cisco_ios_spec.rb
  spec/unit/puppet/provider/ios_radius_server_group/test_data.yaml
  spec/unit/puppet/type/ios_radius_server_group.rb
Labels: feature

#372 (FM-7554) cleanup can_have_no_match logic
  lib/puppet/provider/ios_aaa_accounting/command.yaml
  lib/puppet/provider/ios_aaa_authentication/command.yaml
  lib/puppet/provider/ios_aaa_authorization/command.yaml
  lib/puppet/provider/ios_aaa_session_id/command.yaml
  lib/puppet/provider/ios_additional_syslog_settings/command.yaml
  lib/puppet/provider/ios_interface/command.yaml
  lib/puppet/provider/ios_network_dns/command.yaml
  lib/puppet/provider/ios_network_trunk/command.yaml
  lib/puppet/provider/ios_radius_global/command.yaml
  lib/puppet/provider/ios_snmp_global/command.yaml
  lib/puppet/provider/ios_stp_global/command.yaml
  lib/puppet/provider/network_interface/command.yaml
  lib/puppet/provider/network_snmp/command.yaml
  lib/puppet/provider/network_trunk/command.yaml
  lib/puppet/provider/network_vlan/command.yaml
  lib/puppet/provider/port_channel/command.yaml
  lib/puppet/provider/syslog_settings/command.yaml
  lib/puppet_x/puppetlabs/cisco_ios/utility.rb
Labels: maintenance

#374 (FM-8441) - Remove code that removes additional spaces
  lib/puppet_x/puppetlabs/cisco_ios/utility.rb
  spec/acceptance/banner_spec.rb
  spec/spec_helper_local.rb
  spec/unit/puppet/provider/snmp_user/cisco_ios_spec.rb
Labels: bugfix

#373 (maint) return cli_command errors as JSON
  tasks/cli_command.rb
Labels: bugfix
